import { initCommands } from "models/system/command.model";
import { initSlot } from "models/system/slot.slice";
import { initSettings } from "@/reducers/Settings/settings.model";
import { initFeilds } from "models/system/feild.model";
import { initPositions } from "models/system/positions.model";
import { initViews } from "models/system/views.model";
import { initColors } from "models/system/colors.model";
import { initNotifays } from "models/system/notifications.model";
import { initLogs } from "models/system/logs.model";
import { initTrees } from "models/system/tree.model";
import { initKeys } from "models/system/keys.model";
import { initLangs } from "models/system/lang.model";
import { initCashing } from "@/data/system/cash.model";
import { initToasts } from "@/data/system/toasts.model";
export function initSystem() {
  initCommands();
  initFeilds();
  initSlot();
  initColors();
  initViews();
  initPositions();
  initNotifays();
  initSettings();
  initLogs();
  initTrees();
  initKeys();
  initLangs();
  initCashing();
  initToasts();
}
